### ISSUE TITLE
Getting by without SUPER privilege

### ISSUE THREAD

**Issue by teu** [github/gh-ost#132]
Hi, 
we have case in which we would like to use gh-ost with AWS RDS. However, the problem with this managed database store is that it does not grant us the SUPER privilege.
Is there any way of using gh-ost and not having SUPER on the server?
Thanks

**Comment by shlomi-noach** [comment]
looking into this

**Comment by shlomi-noach** [comment]
The first blocker I see right away is that `SUPER` is required for `STOP SLAVE` and `START SLAVE`.

Why do we need these two in the first place? Because `gh-ost` may be asked to switch `binlog_format` to `ROW`. In which case it issues:

- `set global binlog_format='ROW'`
- `set session binlog_format='ROW'`

However if the replica was running with `STATEMENT`, merely changing to `ROW` means nothing; the replication must be `STOP`ped and `START`ed for the setting to take effect. `gh-ost` does not want to assume it was set up correctly before running; therefore it _always_ issues a `STOP & START`.

We _could_ add a flag saying `--trust-me-this-is-rbr` to skip the above. I don't like it, but it's possible.

**Comment by SuperQ** [comment]
It should be possible to pre-test for RBR and not require `SUPER`.

**Comment by shlomi-noach** [comment]
@SuperQ how can you you confirm without doubt the replica is using RBR? Please read again my comment.

**Comment by shlomi-noach** [comment]
To elaborate: you see a replica. It _says_ it has `binlog_format=ROW`. Fact: it may replicate via `SBR`, because _maybe_ someone `set global binlog_format=ROW` without restarting replication.

It sounds far fetched, but in fact is a classic case in `--switch-to-rbr`

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/156 will close this Issue, and will make it possible to run `gh-ost` without `SUPER` privilege.

**Comment by shlomi-noach** [comment]
I'm happy to merge #156 , and see thoughts on SBR/RBR in comment: https://github.com/github/gh-ost/pull/156#issuecomment-240351262

**Comment by shlomi-noach** [comment]
`SUPER` is now not required for normal migration, see #156 and release https://github.com/github/gh-ost/releases/tag/v1.0.10

It is still required in `--test-on-replica`, see discussion on https://github.com/github/gh-ost/issues/162 and on #163

**Comment by shlomi-noach** [comment]
[Hooks](https://github.com/github/gh-ost/pull/190) have been merged, and remove the last barrier for `SUPER`. I will write more about this on next release, which is expected early next week, at which time this bug will be closed.

**Comment by shlomi-noach** [comment]
all done
