### ISSUE TITLE
Does gh-ost support distributed databases?

### ISSUE THREAD

**Issue by iwanghc** [github/gh-ost#1390]
For example GoldenDB， it is based on mysql, but the table creation syntax is different.

**Comment by timvaillancourt** [comment]
@iwanghc for the simplified answer is no. `gh-ost` only knows what plain MySQL is.

The more complicated answer is: there are cases where `gh-ost` has been successfully used on distributed MySQL-based databases, such as Vitess. `gh-ost` is able to work on Vitess because its shards still run plain MySQL, so `gh-ost` doesn't really "know" Vitess is there. For many other MySQL-compatible databases this assumption probably will not hold true, however

**Comment by iwanghc** [comment]
Thanks！
