### ISSUE TITLE
Reduce minimum max-lag-millis threshold

### ISSUE THREAD

**Issue by jonahberquist** [github/gh-ost#203]
When we were designing gh-ost, all of our replication lag monitoring had a minimum granularity of 1 second. We have more granularity now, and I'd like to be able to have gh-ost throttled further. I have a branch that reduces the minimum of this threshold from 1000ms to 100ms.

Thoughts on if that is sufficient or if we should allow even less than that?

**Comment by shlomi-noach** [comment]
There are additional consideration to reducing the `maxLagMillisecondsThrottleThreshold` below `1000`:

- `ReplicationLag` still stored as an `int64` -- for _seconds_. This needs to be modified, I deally as `ReplicationLagMillis int64`
- The frequency at which we _inject_ heartbeat events is, right now, every `250ms`. So less granular than the measurement you'd like to take. We would need to either:
  - Increase `gh-ost`'s own frequency
  - Recognize that there's already an external `heartbeat` mechanism and trust it (or fallback onto it if our own internal lag is over the threshold)
- We also need to increase the _check_ frequency. We only _check_ for throttle scenarios once per second.
Because we may only be interested in increasing frequency for _lag_ (that is, I don't know that we would increase poll frequency for `max-load`, for example), we want to decouple the lag-check from the general throttle-check.
- Last, we need to allow for oversampling. Heartbeat injection should oversample the lag check; I would suggest that if we inject `heartbeat` every `100ms`, we should only check for lag as small as `400ms`, potentially as low as `200ms` and not below that value, or else we pay with an error margin that is twice the threshold.

**Comment by shlomi-noach** [comment]
>  ReplicationLag still stored as an int64 -- for seconds. This needs to be modified, I deally as ReplicationLagMillis int64 

Correction: nano-seconds. Which is good.

**Comment by shlomi-noach** [comment]
> The frequency at which we inject heartbeat events is, right now, every 250ms

Correction: `1s`

**Comment by shlomi-noach** [comment]
> We also need to increase the check frequency. We only check for throttle scenarios once per second. 

Elaborate: 

- `1s` check interval for all control-replicas. Do we really want to check each control replica `10` times a second?
- The inspector replica is checked separately, as desired -- already decoupled.

**Comment by shlomi-noach** [comment]
And forget about what I said on the oversampling.

**Comment by shlomi-noach** [comment]
Just... Forget everything.

**Comment by shlomi-noach** [comment]
Further notes: 

- We wouldn't want to burden replicas with so many checks if the threshold is `1s` or above, anyhow.
- We wouldn't want to burden the replicas with so many checks if `replication-lag-query` is empty (i.e. the only tool we have is `show slave status` with `1s` granularity)
- So we can continue to pool only once per second if not both apply.
- But since both the above variables are dynamic, we do need to support an immediate change in behavior should both apply.

**Comment by shlomi-noach** [comment]
So I'm making `--heartbeat-interval-millis` configurable. Default will be `500ms` and can be reduced as low as `100ms`.

**Comment by shlomi-noach** [comment]
Quite a few changes have been pushed, but I suspect this change further implies that the throttling code should be completely independent from all throttling checks. To elaborate:

Before this PR we did a once-per-sec check: "should we throttle". In that check we would check for flag files, `max-load`, lag, etc.

But now we want the lag to be checked, say, `10` times per sec. But we only want to keep the `max-load` check at once per sec. So the two need to go completely different routes. 

And then, how often do we even as the question "should we throttle"? If we're checking for lag `10` times per sec, we must ask "should we throttle" at least `10` times per sec, or else why do we check so frequently? So the question must decouple from all measurements.

And this calls for a larger code refactoring than expected; no big deal, but more changes coming.

**Comment by shlomi-noach** [comment]
This is actually running in production right now, having passed tests. 

Whoa whoa whoa! Insane. Running with `max-lag-millis=500`, `--heartbeat-interval-millis=100`, no `nice-ratio`, `gh-ost` aggressively runs the migration while all production replicas lag is kept _below_ `1s`!

**Comment by shlomi-noach** [comment]
It's a pity I can't say the name of the table on which this is running. It's _you know who_

**Comment by shlomi-noach** [comment]
This is now merged. Closing. Will iterate if need be.

**Comment by tomkrouper** [comment]
> It's you know who

there is table called Voldemort? :trollface:

**Comment by shlomi-noach** [comment]
@tomkrouper I told you not to say his name!
