### ISSUE TITLE
Discussion: redefine critical-load behavior during cut-over

### ISSUE THREAD

**Issue by shlomi-noach** [github/gh-ost#216]
cut-over is the time where tables are locked. It is naturally a time where connections pile up.
meeting `critical-load` during cut-over can _make sense_. Do we want to bail out when it is met?

A suggestion by the @github/database-infrastructure team is to rollback the cut-over, and go to "postponed" mode (or just retry the cut-over as normal)

In such case, we also need to allow for a grace period before checking the thresholds again. Because as we exit the cut-over, we're back in the realm where `critical-load` should indeed fail the migration. So, say, give a couple seconds? Should this be configurable? How so?

**Comment by shlomi-noach** [comment]
Additional options:

support a specialized `cut-over-load`?

**Comment by shlomi-noach** [comment]
additional option:

rollback when we meet `critical-load/2` (or what have you, say `80%`)

**Comment by jonahberquist** [comment]
Keeping this fast and responsive to load is good. We should continue to avoid allowing ourselves to be at critical-load for several seconds.

I'm actually impressed with the way this handles itself so that the huge load spike we saw caused gh-ost to back out immediately and we didn't see any production issues (apart from the migration itself dying).

I do like the idea of catching something less than critical load and falling back to postponed mode so that we don't have to start the migration again. The most annoying part there is that we have to go through the whole migration right now, but there's another use case for https://github.com/github/gh-ost/issues/205.

**Comment by shlomi-noach** [comment]
I think our problem would be that, taking the `threads_running` threshold as an example, when it spikes, it spikes real fast. Even if we measure 10 times per sec, we might not be able to catch `critical-load/2` or `critical=load*0.9` in time, before it meets the threshold.

Given that the bail out we saw was on our _you know who_, one of our busiest tables (if not the busiest), and that this only happened once, and, once it happened, `gh-ost` bailed out gracefully and without impact on production, we may choose to tag this as a non-issue.

If we implement #205 then that puts `gh-ost` in a completely different place indeed, and makes the `critical-load` a non-issue by definition.

**Comment by shlomi-noach** [comment]
additional option:

- keep it as it is today

**Comment by shlomi-noach** [comment]
meanwhile we're implicitly actively working on "keep it as it is today", i.e. not really doing anything about it.
We only had once incident where this happened, on `repositories`, and though `gh-ost` bailed out, it did so gracefully and everything was _fine_.
I'm going to close this issue. If we see this happen more, and if it becomes a pain, then we can reconsider.

**Comment by shlomi-noach** [comment]
https://github.com/github/gh-ost/pull/266 (`--critical-load-interval-millis`) solves this.
