### ISSUE TITLE
Warming up InnoDB buffer pool

### ISSUE THREAD

**Issue by pbitty** [github/gh-ost#245]
This is not specific to gh-ost but I'm wondering if anyone is using techniques for warming up the InnoDB buffer pool prior to cutover.  In my initial tests I can see that the some `_gho` table data does get loaded into the buffer pool during migration, but this is only based on the write queries from the row copy and the binlog events.

I'm working on a utility to stream `SELECT` live queries on the original table to the `_gho` table.  This will let us warm up the buffer pool with the same query patterns that are already hitting the original table.  We're doing this application-side.

I'm curious to know if anyone has insights or techniques to share on this.

I realize this is not specific to gh-ost and I don't want to take discussion away from it.  I am happy to close this issue at anytime.

**Comment by shlomi-noach** [comment]
Fantastic question. We should tackle it ourselves. I don't recall we've seen a write latency increase immediately after cut-over, even for our largest tables, but the problem may yet be just lurking around the corner. 

cc @jonahberquist who may have more insight on our side.

**Comment by SuperQ** [comment]
I've definitely seen latency and IO spikes after doing table flips.  Especially on very large 100+GB tables where the working set can be on the order of 30+G of ram (say, 20% of the buffer pool).

Mirroring some queries to the new tables is a good idea just before cut-over, depending on the table use case.

**Comment by shlomi-noach** [comment]
I guess take-over hooks are the easy answer as far as `gh-ost` is concerned...

**Comment by jonahberquist** [comment]
I did some looking at our table stats graphs for a few recent migrations on large tables and things were mostly uneventful. Mostly read and write latencies didn't increase at the time of cutover.

I say _mostly_ because while latency metrics for inserts/deletes/updates didn't increase, I did see a big increase in the `io_write_latency` metric, but that corresponded to an increase in `io_write` which I'm pretty sure is just because InnoDB was like, "oh, hey, it's a lot less busy now, I'm going to finish writing out these pages." It's an increase in write latency, but not a user-facing one.

Interestingly, for one of the tables I _did_ notice a fetch latency jump for a few minutes right after the cutover -- but not on the master, only on our production replicas.

One of the ways we warm up cold replicas is a script that `ngrep`s MySQL traffic on a production box, grabs all of the SELECT queries, and then pipes them in parallel to the new box.

The same sort of technique could be used to warm up a ghost table -- sniff traffic, grab SELECTs for the table, replace `table` with `_table_gho`, and replay that locally. I think it is probably beyond the scope of gh-ost to do something like that, but tying in to the `row-copy-complete` hook would be the place to kick something off.

**Comment by pbitty** [comment]
Thanks so much for the insight.  Some of our DBs have no read replicas and have a single table - I suspect they will be hit harder by the switch-over.  Testing will tell.

The technique above is pretty much what we're going for - stream SELECTs from prod traffic, replace table name and play them back.  We're doing the streaming application-side as it is currently easier to hook into and deploy than the sniffing approach, but sniffing definitely sounds better in terms of being completely decoupled from any app code.

Using the hooks to kick of a "warm-up" job sounds ideal too.

Closing this issue for now.  If I have anything interesting to add from our experience I'll add it here.

Thx again.
