### ISSUE TITLE
How does gh-ost decide cut-over point and ensure bin log applied?

### ISSUE THREAD

**Issue by jessicalu2016** [github/gh-ost#288]
Hi,

Apologies if this is already documented. If so, I would be much appreciated you could point me to the right documents. 

For "Connect to replica, migrate on master" mode, how does gh-ost decide it's the time to cut over? And replication is asynchronous, replica could lag, how does gh-ost guarantee that all binary logs will be applied to ghost table?

I noticed a statement on "the-fine-print.md" page that "You cannot perform a migration with "connect to replica" if your replica lags." Does that mean "connect to replica" mode won't work even for small lags (e.g less than a few seconds)?

Thanks in advance!

**Comment by ggunson** [comment]
> For "Connect to replica, migrate on master" mode, how does gh-ost decide it's the time to cut over? 

It's ready to attempt cutover (or stay in a state of being ready to cut over) when it's finished copying all the rows to the new table. Since there's generally two processes that create the new table: the by-unique-or-primary-key chunk copying of rows from the old to new table, and applying the parsed binary log changes to the new table. Once the copying of rows is done, all that's left is to get into a state where all the binary log changes are applied and the tables can be swapped.

> And replication is asynchronous, replica could lag, how does gh-ost guarantee that all binary logs will be applied to ghost table?

It does require some locking; it needs to lock the old table, make sure all the binary log changes to it are applied to the new table, and then proceed to cutover. If this takes more than gh-ost's `lock_wait_timeout` it will bail and wait and retry (so that database operations aren't stalled indefinitely if replication is behind and it takes too long to catch up and apply the changes).

More info on cutover: https://github.com/github/gh-ost/blob/master/doc/cut-over.md

https://github.com/github/gh-ost/blob/master/doc/what-if.md

> Does that mean "connect to replica" mode won't work even for small lags (e.g less than a few seconds)?

@shlomi-noach will have more specifics about the settings you'd be concerned with.

**Comment by jessicalu2016** [comment]
@ggunson Thanks for clarification!

**Comment by shlomi-noach** [comment]
Thanks @ggunson . To elaborate more on how `gh-ost` actually knows the relevant binary logs have been consumed: `gh-ost` uses a helper table (the `..._ghc_` table). At the cut-over phase, and immediately after locking your original table, `gh-ost` writes a magic entry to the helper table (which is unlocked). Because this entry is written after your original table gets locked, the matching binlog entry is _later_ than any last entries on your original tables.

`gh-ost` then intercepts that entry in the binary logs (if you're in "connect to replica" then it's the replica's binary logs). When it reads the magic entry, it _knows_ it also processed the last binary log entries needed to sync the original table an the _ghost_ table.

Small lags are fine, and you define the lag threshold. If your replica constantly lags by an hour -- bad position. If you replica typically lags a couple seconds, and just happens to spike and lag by an hour -- all is well, `gh-ost` will accommodate. `gh-ost` will only actually cut-over when replication lag is low.

**Comment by jessicalu2016** [comment]
@shlomi-noach ah I see. things pretty clear now. Thanks so much for fast reply!
