### ISSUE TITLE
gh-ost not support rename one table to another 

### ISSUE THREAD

**Issue by rudy-gao** [github/gh-ost#576]
Hello, I think gh-ost not support rename one table to another 
My ddl is flollowing:
1. My old table is 
```
CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
```
2. My ddl is
```
 alter table t1 rename to t2;
```
3.  gh-ost init applier as following
```
create /* gh-ost */ table test._t1_gho like test.t1;

```
then gh-ost apply ddl on _t1_gho table using follow func:
```
func (this *Applier) AlterGhost() error {
	query := fmt.Sprintf(`alter /* gh-ost */ table %s.%s %s`,
		sql.EscapeName(this.migrationContext.DatabaseName),
		sql.EscapeName(this.migrationContext.GetGhostTableName()),
		this.migrationContext.AlterStatement,
	)
}
```
but because alter statement is : `rename to t2` so alter table is 
```
alter /* gh-ost */ table _t1_gho rename to t2;
```
finally _t1_gho missing

**Comment by zmoazeni** [comment]
Renaming tables is a fast operation. It just changes the MySQL metadata. So you shouldn't need gh-ost for it. You can just run the DDL directly.

**Comment by rudy-gao** [comment]
Yes, I konw that, but renaming table is an `alter table` statement, it may be executed by gh-ost, so I think gh-ost should report error. In our system, DDL is executed by robot, not human, then causing bug.

**Comment by zmoazeni** [comment]
I agree that it would have been nice if gh-ost reported an error early to be friendly, but I don't agree that just because it's `alter table` statement, using gh-ost is appropriate. 

I personally think there needs to be some level of evaluation when determining if gh-ost is the right tool for the job. I don't know how that looks for your system, but I wouldn't agree that gh-ost is a complete drop-in replacement for MySQL's `alter table` syntax.

For example each item in the this list that has "Only Modifies Metadata?" is perfectly fine to run without gh-ost. https://dev.mysql.com/doc/refman/5.7/en/innodb-create-index-overview.html

**Comment by rudy-gao** [comment]
Yes, I also agree that renaming table is not used gh-ost, I think gh-ost should report an error early, rather then excuting '''alter /* gh-ost */ table _t1_gho rename to t2'''

**Comment by shlomi-noach** [comment]
Let me look into it (report error on `RENAME` operation)
