### ISSUE TITLE
How to avoid the slave replicate lag when run the gh-ost on master db

### ISSUE THREAD

**Issue by yiwenshuo** [github/gh-ost#622]
I run the gh-ost command on the master db, the master db have a slave db. The command is 

./gh-ost --host='xxxxx' --port=3306 --user= xxxx  --password='xxxxx' --database='xxxxxx' --chunk-size=100000  --allow-on-master --execute  --initially-drop-ghost-table --exact-rowcount --initially-drop-old-table  --alter="modify column id bigint not null auto_increment"  --table='message' --assume-rbr --max-lag-millis=2000

But more than 2s replicate lag, how should I do ?

**Comment by shlomi-noach** [comment]
Can you be more specific? How much more than `2s`? If only slightly more, it makes sense. The algorithm is greedy, and for as long as lag is `< 2s` `gh-ost` will pursue, and will only kick in throttling once lag `> 2s`. So that's natural.

However, I see you went far and set `--chunk-size=100000`. This is a recipe for replication lag. FYI we use `--chunk-size=100`, no more.

**Comment by yiwenshuo** [comment]
@shlomi-noach  THX
