### ISSUE TITLE
Move to Go modules rather than vendored dependencies?

### ISSUE THREAD

**Issue by zmoazeni** [github/gh-ost#739]
Howdy, if #738 works, I was wondering what the opinions on moving to [Go modules](https://github.com/golang/go/wiki/Modules) were rather than committing the dependencies directly.

I didn't see any existing conversations on this topic.

**Comment by zmoazeni** [comment]
Oh two other notes. This is somewhat related to #727 and would allow us to be able to develop gh-ost outside the `GOPATH`

**Comment by shlomi-noach** [comment]
On moving to Go modules: no strong opinions. Since creating orchestrator & gh-ost I've seen so many packaging themes come and go, that I'm glad I didn't commit to any of them previously. I can't say I'm 💯 sure Go modules will be wonderful, but it's the standard now (until the next thing?) so we can try that out.

**Comment by zmoazeni** [comment]
Right on. Yeah I'm hoping modules are here to stay. I do think what you have currently has worked well. I'll work something up and submit a PR.

**Comment by zmoazeni** [comment]
Ah this is going to take some work. There's a few dependencies that have changes that aren't upstream.

**Comment by timvaillancourt** [comment]
Go modules has been implemented in https://github.com/github/gh-ost/pull/935. Closing this 🎉

**Comment by chenrui333** [comment]
@timvaillancourt Any timeline to release the `go modules` change? Thanks!
